export const elisaCatalogColumnIds = [
  "human",
  "mouse",
  "rat",
  "bovine",
  "canine",
  "chicken",
  "goat",
  "monkey",
  "porcine",
  "non-human",
] as const;

export type ElisaCatalogColumnId = (typeof elisaCatalogColumnIds)[number];

export type ElisaCatalogRow = Readonly<{
  availableFor: readonly ElisaCatalogColumnId[];
  id: string;
  label: string;
}>;

export const elisaCatalogRows = [
  { id: "target-001", label: "Adiponectin", availableFor: ["human","mouse"] },
  { id: "target-002", label: "Albumin", availableFor: ["human"] },
  { id: "target-003", label: "Apo A1", availableFor: ["human","monkey"] },
  { id: "target-004", label: "BAFF", availableFor: ["human"] },
  { id: "target-005", label: "BD-1", availableFor: ["human"] },
  { id: "target-006", label: "BD-2", availableFor: ["human"] },
  { id: "target-007", label: "BD-4", availableFor: ["human"] },
  { id: "target-008", label: "bFGF", availableFor: ["human"] },
  { id: "target-009", label: "BMP-2", availableFor: ["human"] },
  { id: "target-010", label: "BMP-4", availableFor: ["human"] },
  { id: "target-011", label: "CCL19", availableFor: ["human"] },
  { id: "target-012", label: "CCL21", availableFor: ["mouse"] },
  { id: "target-013", label: "CCL4/MIP-1β", availableFor: ["monkey"] },
  { id: "target-014", label: "CRP", availableFor: ["human","mouse"] },
  { id: "target-015", label: "CTACK", availableFor: ["human"] },
  { id: "target-016", label: "CXCL1/GROα/NAP-3", availableFor: ["human"] },
  { id: "target-017", label: "CXCL16", availableFor: ["human"] },
  { id: "target-018", label: "CXCL4", availableFor: ["human","mouse"] },
  { id: "target-019", label: "CXCL6/GCP-2", availableFor: ["human"] },
  { id: "target-020", label: "Dickkopf-1", availableFor: ["human","mouse"] },
  { id: "target-021", label: "EGF", availableFor: ["human","rat"] },
  { id: "target-022", label: "Carcino Embryonic Antigen", availableFor: ["human"] },
  { id: "target-023", label: "Eotaxin", availableFor: ["human"] },
  { id: "target-024", label: "Alpha Fetoprotein", availableFor: ["human"] },
  { id: "target-025", label: "FGF-21", availableFor: ["human","mouse"] },
  { id: "target-026", label: "G-CSF", availableFor: ["human"] },
  { id: "target-027", label: "GM-CSF", availableFor: ["human","mouse","rat"] },
  { id: "target-028", label: "Granzyme B", availableFor: ["human"] },
  { id: "target-029", label: "GRO beta", availableFor: ["human"] },
  { id: "target-030", label: "GRO-γ/CXCL3", availableFor: ["human"] },
  { id: "target-031", label: "HB-EGF", availableFor: ["human"] },
  { id: "target-032", label: "HGF", availableFor: ["human"] },
  { id: "target-033", label: "IFN-α", availableFor: ["human","mouse","monkey"] },
  { id: "target-034", label: "IFN-α pan", availableFor: ["monkey"] },
  { id: "target-035", label: "IFN-α2", availableFor: ["human"] },
  { id: "target-036", label: "IFN-β", availableFor: ["human","mouse"] },
  { id: "target-037", label: "IFN-γ", availableFor: ["human","mouse","rat","bovine","chicken","porcine"] },
  { id: "target-038", label: "IgA", availableFor: ["human","mouse","rat","monkey"] },
  { id: "target-039", label: "IgE", availableFor: ["human","mouse","rat"] },
  { id: "target-040", label: "IGF-BP1", availableFor: ["human"] },
  { id: "target-041", label: "IGF-I", availableFor: ["mouse"] },
  { id: "target-042", label: "IgG", availableFor: ["human","mouse","rat","bovine"] },
  { id: "target-043", label: "IgG1", availableFor: ["mouse","rat"] },
  { id: "target-044", label: "IgG2a", availableFor: ["mouse","rat"] },
  { id: "target-045", label: "IgG2b", availableFor: ["mouse","rat"] },
  { id: "target-046", label: "IgG3", availableFor: ["mouse"] },
  { id: "target-047", label: "IgG4", availableFor: ["human"] },
  { id: "target-048", label: "IgM", availableFor: ["human","mouse","rat","monkey"] },
  { id: "target-049", label: "IL-10", availableFor: ["human","mouse","rat","monkey","porcine"] },
  { id: "target-050", label: "IL-11", availableFor: ["human"] },
  { id: "target-051", label: "IL-12/23p40", availableFor: ["human","mouse","monkey"] },
  { id: "target-052", label: "IL-12p70", availableFor: ["human","mouse","monkey"] },
  { id: "target-053", label: "IL-13", availableFor: ["human","mouse","rat","monkey"] },
  { id: "target-054", label: "IL-15", availableFor: ["human","mouse"] },
  { id: "target-055", label: "IL-16", availableFor: ["mouse"] },
  { id: "target-056", label: "IL-17A", availableFor: ["human","mouse","rat"] },
  { id: "target-057", label: "IL-17A/F Heterodimer", availableFor: ["human","mouse"] },
  { id: "target-058", label: "IL-17B", availableFor: ["human","mouse"] },
  { id: "target-059", label: "IL-17D", availableFor: ["mouse"] },
  { id: "target-060", label: "IL-17E", availableFor: ["mouse"] },
  { id: "target-061", label: "IL-17E/IL-25", availableFor: ["human"] },
  { id: "target-062", label: "IL-17F", availableFor: ["human","mouse"] },
  { id: "target-063", label: "IL-18", availableFor: ["human","mouse","rat"] },
  { id: "target-064", label: "IL-1RA", availableFor: ["human","monkey"] },
  { id: "target-065", label: "IL-1α", availableFor: ["human","mouse","rat"] },
  { id: "target-066", label: "IL-1β", availableFor: ["human","mouse","rat","monkey","porcine"] },
  { id: "target-067", label: "IL-2", availableFor: ["human","mouse","rat","monkey","porcine"] },
  { id: "target-068", label: "IL-21", availableFor: ["human","mouse","monkey"] },
  { id: "target-069", label: "IL-22", availableFor: ["human","mouse","porcine"] },
  { id: "target-070", label: "IL-23", availableFor: ["human","mouse"] },
  { id: "target-071", label: "IL-24", availableFor: ["human"] },
  { id: "target-072", label: "IL-27", availableFor: ["human","mouse"] },
  { id: "target-073", label: "IL-27p28", availableFor: ["mouse"] },
  { id: "target-074", label: "IL-29", availableFor: ["human"] },
  { id: "target-075", label: "IL-2sRα", availableFor: ["human"] },
  { id: "target-076", label: "IL-3", availableFor: ["human"] },
  { id: "target-077", label: "IL-31", availableFor: ["human"] },
  { id: "target-078", label: "IL-32", availableFor: ["human"] },
  { id: "target-079", label: "IL-33", availableFor: ["human","mouse"] },
  { id: "target-080", label: "IL-33R", availableFor: ["mouse"] },
  { id: "target-081", label: "IL-37", availableFor: ["human"] },
  { id: "target-082", label: "IL-38", availableFor: ["human"] },
  { id: "target-083", label: "IL-4", availableFor: ["human","mouse","rat","bovine","goat","monkey","porcine"] },
  { id: "target-084", label: "IL-5", availableFor: ["human","mouse","monkey"] },
  { id: "target-085", label: "IL-6", availableFor: ["human","mouse","rat","monkey","porcine"] },
  { id: "target-086", label: "IL-6Rα", availableFor: ["human"] },
  { id: "target-087", label: "IL-7", availableFor: ["human"] },
  { id: "target-088", label: "IL-8", availableFor: ["human","bovine","canine"] },
  { id: "target-089", label: "IL-9", availableFor: ["human","mouse"] },
  { id: "target-090", label: "Insulin", availableFor: ["human","monkey","porcine"] },
  { id: "target-091", label: "IP-10", availableFor: ["human","mouse"] },
  { id: "target-092", label: "KC", availableFor: ["rat"] },
  { id: "target-093", label: "KC/CXCL1", availableFor: ["mouse"] },
  { id: "target-094", label: "KIM-1", availableFor: ["mouse"] },
  { id: "target-095", label: "Latent TGF-β1", availableFor: ["human"] },
  { id: "target-096", label: "Leptin", availableFor: ["human"] },
  { id: "target-097", label: "lFN-α pan", availableFor: ["human"] },
  { id: "target-098", label: "Lipocalin-2/NGAL", availableFor: ["human"] },
  { id: "target-099", label: "lL-17A", availableFor: ["canine"] },
  { id: "target-100", label: "MCP-1", availableFor: ["human","mouse","rat"] },
  { id: "target-101", label: "MCP-2", availableFor: ["human"] },
  { id: "target-102", label: "MCP-3", availableFor: ["human"] },
  { id: "target-103", label: "M-CSF", availableFor: ["human","mouse"] },
  { id: "target-104", label: "MDC", availableFor: ["mouse"] },
  { id: "target-105", label: "MDC/CCL22", availableFor: ["human"] },
  { id: "target-106", label: "MIG", availableFor: ["human"] },
  { id: "target-107", label: "MIP-1α", availableFor: ["human","mouse","rat"] },
  { id: "target-108", label: "MIP-1β", availableFor: ["human","mouse"] },
  { id: "target-109", label: "MIP-2", availableFor: ["mouse"] },
  { id: "target-110", label: "MMP-1", availableFor: ["human"] },
  { id: "target-111", label: "MMP-2", availableFor: ["human"] },
  { id: "target-112", label: "MMP-3", availableFor: ["human"] },
  { id: "target-113", label: "MMP-7", availableFor: ["human"] },
  { id: "target-114", label: "MMP-9", availableFor: ["human"] },
  { id: "target-115", label: "Neuroserpin", availableFor: ["human"] },
  { id: "target-116", label: "Osteoprotegerin", availableFor: ["human"] },
  { id: "target-117", label: "PAI-1", availableFor: ["human"] },
  { id: "target-118", label: "PD-1", availableFor: ["human","mouse"] },
  { id: "target-119", label: "PDGF-BB", availableFor: ["human","mouse","rat"] },
  { id: "target-120", label: "PD-L1", availableFor: ["human","mouse"] },
  { id: "target-121", label: "Perforin", availableFor: ["human","monkey"] },
  { id: "target-122", label: "PIGF-1", availableFor: ["human"] },
  { id: "target-123", label: "primates IFN-γ", availableFor: ["non-human"] },
  { id: "target-124", label: "progranulin", availableFor: ["human"] },
  { id: "target-125", label: "RANTES", availableFor: ["human","mouse"] },
  { id: "target-126", label: "Resistin", availableFor: ["human","mouse"] },
  { id: "target-127", label: "sCD40L", availableFor: ["human"] },
  { id: "target-128", label: "SCF", availableFor: ["human","rat"] },
  { id: "target-129", label: "SDF-1α", availableFor: ["human"] },
  { id: "target-130", label: "Serum Albumin", availableFor: ["mouse"] },
  { id: "target-131", label: "Serum Amyloid A", availableFor: ["human"] },
  { id: "target-132", label: "sICAM-1", availableFor: ["human"] },
  { id: "target-133", label: "Siglec-9", availableFor: ["human"] },
  { id: "target-134", label: "sRANK Ligand", availableFor: ["human","mouse"] },
  { id: "target-135", label: "ST2", availableFor: ["human"] },
  { id: "target-136", label: "TGF-alpha", availableFor: ["human"] },
  { id: "target-137", label: "TGF-β1", availableFor: ["human","mouse","rat","monkey","porcine"] },
  { id: "target-138", label: "Thrombopoietin", availableFor: ["human"] },
  { id: "target-139", label: "Tie-2", availableFor: ["human"] },
  { id: "target-140", label: "TIMP-1", availableFor: ["human"] },
  { id: "target-141", label: "TIMP-4", availableFor: ["human"] },
  { id: "target-142", label: "TL-1A", availableFor: ["human"] },
  { id: "target-143", label: "TNF-α", availableFor: ["human","mouse","rat","monkey","porcine"] },
  { id: "target-144", label: "TNF-β", availableFor: ["human"] },
  { id: "target-145", label: "TSLP", availableFor: ["mouse"] },
  { id: "target-146", label: "TWEAK", availableFor: ["human"] },
  { id: "target-147", label: "VCAM-1", availableFor: ["human"] },
  { id: "target-148", label: "VEGF", availableFor: ["mouse","rat"] },
  { id: "target-149", label: "VEGF-A", availableFor: ["human"] },
  { id: "target-150", label: "Vitamin D Binding Protein", availableFor: ["human"] },
  { id: "target-151", label: "β-NGF", availableFor: ["human"] },
] as const satisfies readonly ElisaCatalogRow[];
