import type { YeastTwoHybridContent } from "@/content/yeast-two-hybrid/types";

export const jaYeastTwoHybridContent = {
  metadata: {
    title: "Yeast Two Hybrid | 東方純一",
    description: "酵母転写因子GAL4を基盤とするツーハイブリッドシステム。20年のサービス実績",
  },
  title: "Yeast Two Hybrid",
  intro: "酵母転写因子GAL4を基盤とするツーハイブリッドシステム。20年のサービス実績",
  backToServices: "主要サービスへ戻る",
  overview: {
    title: "サービス概要",
  },
  systemSelectorLabel: "ツーハイブリッド系",
  systems: [
    {
      id: "membrane",
      kind: "membrane",
      label: "膜系ツーハイブリッド",
      subtitle: "Split-Ubiquitin",
      body: "膜タンパク質酵母ツーハイブリッドシステムでは、ユビキチンC末端は、従来の酵母ツーハイブリッドで用いられる転写タンパク質GAL4のDNA結合ドメインに相当し、BaitおよびTranscription Activator LexA-VP16と連結されます。一方、ユビキチンN末端（113G変異）は、従来の酵母ツーハイブリッドで用いられるGAL4の転写活性化ドメインに相当し、PreyまたはLibraryと連結できます。",
      featureTitle: "ベイトベクターの選択",
      specificationTitle: "技術的特長",
      consultation: {
        title: "サービス内容の詳細に関するお問い合わせ",
        emails: [
          { id: "market", email: "market@easternpurity.com" },
          { id: "shanghai-genomics", email: "info@shanghaigenomics.com" },
        ],
      },
      features: [
        { id: "feature-1", title: "pBT3-SUC", description: "N-Ter/Lumenal\nC-Ter/Cytosolic" },
        { id: "feature-2", title: "pBT3-STE", description: "N-Ter/Lumenal/Cytosolic\nC-Ter/Cytosolic" },
        { id: "feature-3", title: "pBT3-N", description: "N-Ter/Cytosolic\nC-Ter/Lumenal/Cytosolic" },
        { id: "feature-4", title: "pDHB1", description: "N-Ter/Cytosolic\nC-Ter/Cytosolic" },
      ],
      specifications: [
        { id: "specification-1", label: "ユビキチンは細胞質に局在するため、タンパク質は核内に移行する必要がありません" },
        { id: "specification-2", label: "ユビキチンは分子量が小さく、タンパク質相互作用への影響も比較的小さい" },
        { id: "specification-3", label: "生細胞の生理的状態でタンパク質相互作用を研究できます" },
        { id: "specification-4", label: "タンパク質の翻訳後修飾の過程を保持します" },
        { id: "specification-5", label: "異なる膜タンパク質構造には、異なる細胞内局在シグナルベクターを用います" },
      ],
    },
    {
      id: "nuclear",
      kind: "nuclear",
      label: "核系ツーハイブリッド",
      subtitle: "GAL4",
      body: "酵母ツーハイブリッド法は、タンパク質間相互作用の解析に用いられます。転写因子GAL4は、二つの独立したドメイン（Binding Domain、BD、およびActivation Domain、AD）に分けられます。BDはベイトタンパク質と融合され、cDNAライブラリーの遺伝子はAD-LIBRARY発現ベクター上に構築されます。ベイトタンパク質と未知タンパク質が相互作用して複合体を形成すると、ADとBDが近接し、レポーター遺伝子の転写が開始されます。これにより、未知タンパク質をスクリーニングし、同定できます。",
      sampleStandardsTitle: "サンプル基準",
      sampleStandards: [
        { id: "cell-sample", title: "細胞サンプル", description: ">1X107" },
        { id: "animal-tissue", title: "動物組織", description: ">1g" },
        { id: "plant-sample", title: "植物サンプル", description: ">2g" },
        { id: "total-rna", title: "総RNA", description: ">300ug" },
      ],
      cdnaLibrary: {
        title: "cDNA Library Available for Yeast Two Hybrid",
        categories: [
            {
              id: "human-cdna-library",
              title: "Human cDNA Library",
              entries: [
                { id: "human-lymphocyte-matchmaker", label: "lymphocyte Matchmaker" },
                { id: "human-fetal-brain-matchmaker", label: "Fetal Brain Matchmaker" },
                { id: "human-hela-matchmaker", label: "HeLa Matchmaker" },
                { id: "human-liver-matchmaker", label: "Liver Matchmaker" },
                { id: "human-fetal-liver-matchmaker", label: "Fetal Liver Matchmaker" },
                { id: "human-leukocyte-matchmaker", label: "Leukocyte Matchmaker" },
                { id: "human-spleen-matchmaker", label: "Spleen Matchmaker" },
                { id: "human-kidney-matchmaker", label: "Kidney Matchmaker" },
                { id: "human-pulmonary-alveolar-epithelial-cells", label: "Pulmonary Alveolar Epithelial cells" },
                { id: "human-endometrium-normal-tumour", label: "Endometrium Normal & Tumour" },
                { id: "human-retina-macula-peripheral-rpe", label: "Retina Macula:Periphera:RPE=1:3:3" },
              ],
            },
            {
              id: "mouse-cdna-library",
              title: "Mouse cDNA Library",
              entries: [
                { id: "mouse-testis-matchmaker", label: "Testis Matchmaker" },
                { id: "mouse-kidney-matchmaker", label: "Kidney Matchmaker" },
                { id: "mouse-embryo-matchmaker", label: "Embryo Matchmaker" },
                { id: "mouse-mixture-library", label: "Brain/Jejunum/Testis/Bat/Liver (mixture-Library)" },
              ],
            },
            {
              id: "plant-cdna-library",
              title: "Plant cDNA Library",
              entries: [
                { id: "plant-arabidopsis", label: "シロイヌナズナ Arabidopsis" },
                { id: "plant-rice", label: "イネ Rice" },
                { id: "plant-wheat", label: "ムギ類 Wheat" },
                { id: "plant-tomato", label: "トマト Tomato" },
                { id: "plant-goji-berry", label: "クコ Goji Berry" },
                { id: "plant-wild-strawberry", label: "野生イチゴ Wild Strawberry" },
                { id: "plant-cucumber", label: "キュウリ Cucumber" },
                { id: "plant-pumpkin", label: "カボチャ Pumpkin" },
                { id: "plant-poplar", label: "ポプラ Poplar" },
                { id: "plant-watermelon", label: "スイカ Watermelon" },
                { id: "plant-carrot", label: "ニンジン Carrot" },
                { id: "plant-liriodendron", label: "ユリノキ Liriodendron" },
                { id: "plant-spinach", label: "ホウレンソウ Spinach" },
                { id: "plant-artemisia-annua", label: "クソニンジン Artemisia Annua" },
                { id: "plant-puncturevine", label: "ハマビシ Puncturevine" },
                { id: "plant-corn", label: "トウモロコシ Corn" },
                { id: "plant-caitai", label: "サイシン" },
                { id: "plant-baimai", label: "ヒャクミャク" },
              ],
            },
            {
              id: "other-cdna-library",
              title: "Other cDNA Library",
              entries: [
                { id: "other-drosophila-mixture-library", label: "キイロショウジョウバエ/(胚 16hr、幼虫、成虫) (mixture- Library)" },
                { id: "other-schistosoma-japonicum-mixture-library", label: "日本住血吸虫/(14-28日)M/F (mixture- Library)" },
                { id: "other-pig-alveolar-macrophage", label: "ブタ/肺胞マクロファージ" },
                { id: "other-mosquito-intestine", label: "蚊/腸管" },
                { id: "other-zebrafish-embryo", label: "ゼブラフィッシュ/胚 tuebingen 0.5mm/26h" },
                { id: "other-tilapia-lymphocyte", label: "ティラピア/リンパ球" },
                { id: "other-pearl-oyster-blood", label: "マルテンスパールオイスター/血液" },
                { id: "other-medaka", label: "メダカ" },
                { id: "other-whiteleg-shrimp", label: "バナメイエビ" },
                { id: "other-chinese-mitten-crab-hemolymphocyte", label: "チュウゴクモクズガニ/血リンパ球" },
                { id: "other-chinese-softshell-turtle", label: "チュウゴクスッポン" },
              ],
            },
        ],
      },
    },
  ],
} as const satisfies YeastTwoHybridContent;
