import type { AntibodyProductsContent } from "@/content/antibody-products/types";
import { zhAntibodyProductsContent } from "@/content/antibody-products/zh";

export const jaAntibodyProductsContent = {
  metadata: {
    title: "抗体および対応担体製品 | 東方純一",
    description: "GNI Anti-Flag モノクローナル抗体、HRP結合抗体、アフィニティゲル、磁気ビーズ、全タグ抗体シリーズ。",
  },
  eyebrow: "GNI® 抗体シリーズ",
  title: "抗体および対応担体製品",
  intro: "タグ抗体、HRP結合抗体、Affinity Gel、Magnetic Beadsの製品情報です。技術仕様は提供資料に基づきます。在庫と出荷予定はお問い合わせ時にご確認ください。",
  backToProducts: "主要製品へ戻る",
  products: [
    {
      id: "mab",
      title: "Anti-Flag マウスモノクローナル抗体",
      subtitle: "Anti-Flag Mouse Monoclonal Antibody",
      experimentImageAlt: "Anti-Flagマウスモノクローナル抗体の実験バンド画像",
      details: [
        { id: "product-name", label: "製品名", value: "Anti-Flag Tag (1E6) Monoclonal Antibody" },
        { id: "source", label: "由来", value: "KLH結合合成Flagタグペプチドで動物を免疫して作製" },
        { id: "concentration", label: "濃度", value: "0.5 mg/ml、PBS（pH 7.4）、50% glycerol含有" },
        { id: "applications", label: "用途", value: "WB、Dot、ELISA" },
        { id: "dilution", label: "推奨希釈", value: "1:500–1:5000" },
        { id: "isotype", label: "アイソタイプ", value: "Mouse IgG2b" },
        { id: "storage", label: "形状 / 保存 / 反応種", value: "液体 / −20°C / All species" },
      ],
      skus: zhAntibodyProductsContent.products[0].skus,
    },
    {
      id: "hrp",
      title: "Anti-Flag-HRP マウスモノクローナル抗体",
      subtitle: "Anti-Flag-HRP Mouse Monoclonal Antibody",
      experimentImageAlt: "Anti-Flag-HRPマウスモノクローナル抗体の実験バンド画像",
      details: [
        { id: "product-name", label: "製品名", value: "Anti-Flag-Tag Antibody Peroxidase (HRP) Conjugated" },
        { id: "source", label: "由来", value: "マウスモノクローナル抗体を最適化条件下でHRPに結合" },
        { id: "concentration", label: "濃度", value: "1 mg/ml、PBS（pH 7.4）、50% glycerol含有" },
        { id: "applications", label: "用途", value: "WB、Dot、ELISA" },
        { id: "dilution", label: "推奨希釈", value: "1:500–1:5000" },
        { id: "isotype", label: "アイソタイプ", value: "Mouse IgG2b" },
        { id: "storage", label: "形状 / 保存 / 反応種", value: "液体 / −20°C / All species" },
      ],
      skus: zhAntibodyProductsContent.products[1].skus,
    },
    {
      id: "affinity-gel",
      title: "Anti-Flag アフィニティゲル",
      subtitle: "Anti-Flag Affinity Gel",
      experimentImageAlt: "Anti-Flagアフィニティゲルの実験画像",
      details: [
        { id: "product-name", label: "製品名", value: "Anti-Flag Tag (1E6) Affinity Gel" },
        { id: "source", label: "由来", value: "Protein A精製マウスIgG2bモノクローナル抗体をSepharose 4Bへ共有結合" },
        { id: "concentration", label: "組成", value: "50%懸濁液。50% glycerol、10 mM sodium phosphate、150 mM sodium chloride（pH 7.4）、0.02% (v/v) ProClin 300含有" },
        { id: "applications", label: "用途", value: "組換えタンパク質精製、免疫沈降" },
        { id: "storage", label: "保存 / 抗体結合量", value: "−20°C / ゲル1 L当たり抗体7.5 g以上" },
        { id: "capacity", label: "結合能", value: "packed resin 1 ml当たりFlag融合タンパク質1.1 mg以上を溶出。IP：5 μl gel / 500 μl粗タンパク質溶液" },
      ],
      skus: zhAntibodyProductsContent.products[2].skus,
    },
    {
      id: "magnetic-beads",
      title: "Anti-Flag 磁気ビーズ",
      subtitle: "Anti-Flag Magnetic Beads",
      experimentImageAlt: "Anti-Flag磁気ビーズの酸溶出実験画像",
      details: [
        { id: "product-name", label: "製品名", value: "Anti-Flag Tag (1E6) Monoclonal Antibody conjugate with Magnetic Beads" },
        { id: "bead-size", label: "ビーズ径", value: "200 nm" },
        { id: "concentration", label: "濃度", value: "10 mg/ml、PBS（pH 7.4）、ProClin 300含有" },
        { id: "applications", label: "用途", value: "Affinity Chromatography、Immunoprecipitation (IP)" },
        { id: "capacity", label: "結合能", value: "≥0.6 mg/ml" },
        { id: "isotype", label: "アイソタイプ", value: "Mouse IgG2b" },
        { id: "storage", label: "形状 / 保存 / 反応種", value: "懸濁液 / 2–8°C / All species" },
      ],
      skus: zhAntibodyProductsContent.products[3].skus,
    },
  ],
  skuLabels: {
    title: "包装規格・カタログ番号",
    packSize: "規格",
    catalogNumber: "カタログ番号",
    availability: "在庫注記",
    availabilityNote: "提供資料では在庫ありと記載。最新在庫はお問い合わせください",
    shippingOrigin: "出荷地",
    incompleteSource: "元画像では規格とカタログ番号が途中で切れているため、製品担当者の確認後に追記が必要です。",
  },
  matrix: {
    title: "全抗体シリーズ",
    originNote: "抗体はマウスで作製されています。",
    tagType: "タグタイプ",
    availabilityHeader: "Available",
    productLabels: { mab: "MAB", hrp: "HRP", "affinity-gel": "Affinity Gel", "magnetic-beads": "Magnetic Beads" },
    available: "提供可",
    unavailable: "資料に記載なし",
    rows: zhAntibodyProductsContent.matrix.rows,
  },
  contact: {
    title: "製品情報を問い合わせる",
    description: "規格、最新在庫、出荷予定、バルク包装については、提供された窓口メールへお問い合わせください。",
    emailLabel: "製品お問い合わせメール",
    email: "Haidiyu@easternpurity.com",
  },
  publications: {
    title: "GNI抗体シリーズ製品を使用して発表された論文",
    items: zhAntibodyProductsContent.publications.items,
  },
} as const satisfies AntibodyProductsContent;
